site_name: Blender Remote
site_description: Remote control Blender with Python and MCP server
site_author: igamenovoer
site_url: https://igamenovoer.github.io/blender-remote/

repo_name: igamenovoer/blender-remote
repo_url: https://github.com/igamenovoer/blender-remote
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.suggest

  icon:
    repo: fontawesome/brands/github

# Simple navigation
nav:
  - Home: index.md

# Basic extensions
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences

# Plugins
plugins:
  - search

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/igamenovoer/blender-remote
      name: GitHub Repository

# Copyright
copyright: Copyright &copy; 2024 igamenovoer