[project]
name = "blender-remote"
version = "0.1.0"
description = "Remote control Blender with Python and MCP server"
authors = ["blender-remote contributors"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
# Development tasks
test = "pytest tests/"
test-cov = "pytest --cov=src/blender_remote --cov=scripts tests/"
lint = "ruff check src/ scripts/ tests/"
format = "black src/ scripts/ tests/"
typecheck = "mypy src/blender_remote scripts"
dev = "pip install -e ."

# Build tasks
build = "python -m build"
clean = "rm -rf build dist *.egg-info"

# Documentation tasks
docs = "sphinx-build -b html docs docs/_build/html"
docs-serve = "python -m http.server --directory docs/_build/html"

[dependencies]
python = ">=3.8,<3.13"
pip = "*"
setuptools = ">=61.0"
wheel = "*"

# Development dependencies
pytest = ">=7.0.0"
pytest-cov = ">=4.0.0"
black = ">=22.0.0"
ruff = ">=0.1.0"
mypy = ">=1.0.0"
pre-commit = ">=3.0.0"

# Documentation dependencies
sphinx = ">=5.0.0"
sphinx-rtd-theme = ">=1.0.0"
sphinx-autodoc-typehints = ">=1.0.0"

[feature.dev.dependencies]
ipython = "*"
jupyter = "*"

[environments]
dev = ["dev"]