[project]
name = "blender-remote"
version = "0.1.0"
description = "Remote control Blender with Python and MCP server"
authors = ["blender-remote contributors"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
# Development tasks
test = "pytest tests/"
test-cov = "pytest --cov=src/blender_remote --cov=scripts tests/"
lint = "ruff check src/ scripts/ tests/"
format = "black src/ scripts/ tests/"
typecheck = "mypy src/blender_remote scripts"
dev = "pip install -e ."

# Build tasks
build = "python -m build"
clean = "rm -rf build dist *.egg-info"

# Documentation tasks
docs = "mkdocs build"
docs-serve = "mkdocs serve"
docs-deploy = "mkdocs gh-deploy --force"

[dependencies]
python = ">=3.8,<3.13"
pip = "*"
setuptools = ">=61.0"
wheel = "*"

# Development dependencies
pytest = ">=7.0.0"
pytest-cov = ">=4.0.0"
black = ">=22.0.0"
ruff = ">=0.1.0"
mypy = ">=1.0.0"
pre-commit = ">=3.0.0"

# Documentation dependencies
mkdocs = ">=1.5.0"
mkdocs-material = ">=9.0.0"
scipy = ">=1.16.0,<2"
rich = ">=14.0.0,<15"
attrs = ">=25.3.0,<26"
omegaconf = ">=2.3.0,<3"
fastmcp = ">=2.10.2,<3"

[feature.dev.dependencies]
ipython = "*"
jupyter = "*"

[environments]
dev = ["dev"]
